apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ILPDFKit
  description: A simple toolkit for filling out PDF forms in iOS.
  annotations:
    business-unit: EverHealth
    github.com/project-slug: drchrono/ILPDFKit
    product: DRC
spec:
  type: service
  lifecycle: production
  owner: EverHealth
  implementation:
    languages:
    - Objective-C
    - Ruby
